require 'open-uri'
require 'nokogiri'
require 'pry'

require './lib/concerns.rb'
require './lib/mac.rb'
require './lib/findMyMac/version.rb'
require './lib/Macs/desktop.rb'
require './lib/Macs/laptop.rb'
require './lib/Macs/unknown.rb'
require './lib/scraper.rb'
require './lib/findMyMac.rb'
